### ISSUE TITLE
Error during npm start

### ISSUE THREAD

**Issue by vivekdhiman** [ractive-foundation/ractive-foundation#181]
Hi, 
npm start giving the below error on windows7. 

C:\Users\vivekdhiman\Desktop\ractive\ractive-foundation>npm start

> ractive-foundation@0.3.0 start C:\Users\vivekdhiman\Desktop\ractive\ractive-fo
> undation
> npm prune && npm install && gulp

npm WARN package.json foundation-sites@5.5.2 No description
\

> phantomjs@1.9.18 install C:\Users\vivekdhiman\Desktop\ractive\ractive-foundati
> on\node_modules\phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-wind
ows.zip
Saving to C:\Users\MANOJK~1\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows
.zip
Receiving...

Error making request.
Error: certificate not trusted
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:927:36)
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket._finishInit (_tls_wrap.js:458:8)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs
\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.18 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.18 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\vivekdhiman\Desktop\ractive\ractive-foundation\npm-debug.l
og

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs
\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! ractive-foundation@0.3.0 start: `npm prune && npm install && gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ractive-foundation@0.3.0 start script 'npm prune && npm i
nstall && gulp'.
npm ERR! This is most likely a problem with the ractive-foundation package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm prune && npm install && gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls ractive-foundation
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\vivekdhiman\Desktop\ractive\ractive-foundation\npm-debug.l
og

**Comment by vivekdhiman** [comment]
Its solved via  : npm config set strict-ssl false
