### ISSUE TITLE
gulp wing throws error

### ISSUE THREAD

**Issue by nathf** [ractive-foundation/ractive-foundation#49]
Here is the error I received when trying to create a new component

`nathan➜~/ractive-foundation(rf_topbar)» gulp wing --name ux-blah                                                                       
[21:14:57] Using gulpfile ~/ractive-foundation/gulpfile.js
[21:14:57] Starting 'wing'...
[21:14:57] 'wing' errored after 8.88 ms
[21:14:57] TypeError: invalid data
    at WriteStream.Socket.write (net.js:614:11)
    at getoptLong.process (~/ractive-foundation/node_modules/node-getopt-long/lib/getopt-long.js:157:24)
    at Object.exports.options (~/ractive-foundation/node_modules/node-getopt-long/lib/getopt-long.js:202:43)
    at module.exports (~/ractive-foundation/tasks/gulpWing.js:33:43)
    at Gulp.<anonymous> (~/ractive-foundation/gulpfile.js:101:2)
    at module.exports (~/ractive-foundation/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (~/ractive-foundation/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (~/ractive-foundation/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (~/ractive-foundation/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20`

**Comment by nathf** [comment]
See PR #50 for this.

**Comment by ScottMaclure** [comment]
Merged.
